config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
resources :users
  # Defines the root path route ("/")
  root "welcome#index"
  resources :categories do
    resources :businesses
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    return unless user.present?

    can :read, :all

    if user.is? :admin
      can :manage, :all
    else
      can :read, :all
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/business.rb
class Business < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :category_businesses, dependent: :destroy
  has_many :categories, through: :category_businesses

  validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, message: 'Amount
                            must be a number' }
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user

  has_many :category_businesses, dependent: :destroy
  has_many :businesses, through: :category_businesses

  validates :icon, presence: true
  validates :name, presence: true
end

app/models/category_business.rb
class CategoryBusiness < ApplicationRecord
  belongs_to :category
  belongs_to :business
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories, dependent: :destroy
  has_many :businesses, dependent: :destroy, foreign_key: 'author_id'
  has_one_attached :avatar
  validates :name, presence: true, length: { maximum: 50 }

  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    categories_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar, { roles: [] }])

    devise_parameter_sanitizer.permit(:account_update, keys: %i[name avatar])
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def new
    @category = Category.includes(:category_businesses).find(params[:category_id])
    @business = @category.businesses.new
    @categories = current_user
  end

  def create
    @category = Category.find(params[:category_id])
    if @category.user != current_user
      flash[:alert] = 'You can only create transaction from your categories'
      redirect_to categories_path
    end
    if business_params[:category_ids].length == 1
      flash[:alert] = 'Must select at least one category'
      redirect_to new_category_business_path(@category)
    else
      @category = Category.find(params[:category_id])
      @business = Business.new(business_params)
      @business.author = current_user

      if @business.save
        flash[:notice] = 'Transaction was created successfully'
        redirect_to @category
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @category = Category.includes(:category_businesses).find(params[:category_id])
    @business = @category.businesses.includes(:category_businesses).find(params[:id])
    @category_businesses = CategoryBusiness.where(category_id: @category.id, business_id: @business.id)
    if @business.destroy
      flash[:success] = 'Transaction was successfully deleted.'
      redirect_to category_path(@category.id)
    else
      flash[:error] = 'Something went wrong'
      render :show
    end
  end

  def business_params
    params.require(:business).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = current_user.categories
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      flash[:success] = 'Category successfully created'
      redirect_to categories_path
    else
      flash[:danger] = 'Something went wrong'
      render 'new'
    end
  end

  def show
    @category = Category.includes(:businesses).find(params[:id])
    @transactions = @category.businesses.order(created_at: :desc)
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:success] = 'category was successfully deleted.'
      redirect_to categories_path
    else
      flash[:error] = 'Something went wrong'
      render :show
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/businesses/_form.html.erb
<div class="big-contain">
  <div class="contain1">
    <h2>Add Transaction</h2>
    <%= form_with model: business, url: category_businesses_path, :html => {:class => 'forming', :id => 'form' }  do |form| %>

      <%= form.label 'Spending name', class: 'fs-5 mb-2 mt-4' %>
      <%= form.text_field :name, autofocus: true, autocomplete: "name", class:'form-control-edit', require: true%>

      <%= form.label :amount, class: 'mb-2 mt-4' %>
      <%= form.text_field :amount, autofocus: true, autocomplete: "amount", class:'form-control-edit mb-4', require: true%>

      <% if business.errors.has_key?(:amount) %>
        <div class="error-message">
          <%= business.errors[:amount].first %>
        </div>
      <% end %>

      <%= form.collection_select(:category_ids, current_user.categories, :id, :name, {}, { multiple: true, class: "form-select mb-3" }) %>
      <%= form.submit "Add Spending", class: 'blahi' %>
    <% end %>
  </div>
</div>

app/views/businesses/new.html.erb
<section class="conatinaer w-70">
  <%= render partial: "form", locals: { business: @business, categories:
  @categories } %>
</section>

app/views/categories/_form.html.erb
<%= form_with model: category, url: categories_path, :html => {:class => 'form', :id => 'form' }  do |f| %>
       <div class="field">
         <%= f.text_field :name, autofocus: true, autocomplete: "text", placeholder: "Enter category name", class: 'fs-5 mb-2 form-control'%>
        <% category.errors.full_messages_for(:name).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
       <div class="field">
       <p class="category-title"> Choose an icon </p>
       <div class="icons">
        <%= f.radio_button :icon, "fast-food-outline" %>
        <%= f.label :icon, :value => "fast-food-outline" do%>
            <ion-icon name="fast-food-outline" class="transaction-img food" value="food"></ion-icon>
        <% end %>
        <%= f.radio_button :icon, "headset" %>
        <%= f.label :icon, :value => "headset" do%>
          <ion-icon name="headset" class="transaction-img headset" value="headset"></ion-icon>
        <% end %>
        <%= f.radio_button :icon, "bulb" %>
        <%= f.label :icon, :value => "bulb" do%>
          <ion-icon name="bulb" class="transaction-img bulb" value="bulb"></ion-icon>
        <% end %>
        <%= f.radio_button :icon, "football" %>
        <%= f.label :icon, :value => "football" do%>
          <ion-icon name="football" class="transaction-img football" value="football"></ion-icon>
        <% end %>
        <%= f.radio_button :icon, "barbell" %>
        <%= f.label :icon, :value => "barbell" do%>
          <ion-icon name="barbell" class="transaction-img barbell" value="barbell"></ion-icon>
        <% end %>
        <!-- car -->
        <%= f.radio_button :icon, "car" %>
        <%= f.label :icon, :value => "car" do%>
          <ion-icon name="car" class="transaction-img car" value="car"></ion-icon>
        <% end %>
        <!-- call -->
        <%= f.radio_button :icon, "call" %>
         <%= f.label :icon, :value => "call" do%>
          <ion-icon name="call" class="transaction-img call" value="call"></ion-icon>
        <% end %>
        <!-- bus -->
        <%= f.radio_button :icon, "book" %>
         <%= f.label :icon, :value => "book" do%>
          <ion-icon name="book" class="transaction-img book" value="Education"></ion-icon>
        <% end %>
        <!-- game-controller -->
        <%= f.radio_button :icon, "game-controller" %>
        <%= f.label :icon, :value => "game-controller" do%>
          <ion-icon name="game-controller" class="transaction-img game-controller" value="Games"></ion-icon>
        <% end %>
        <!-- home -->
        <%= f.radio_button :icon, "home" %>
        <%= f.label :icon, :value => "home" do%>
          <ion-icon name="home" class="transaction-img home" value="home"></ion-icon>
        <% end %>
        <!-- shirt -->
        <%= f.radio_button :icon, "shirt" %>
        <%= f.label :icon, :value => "shirt" do%>
          <ion-icon name="shirt" class="transaction-img shirt" value="shirt"></ion-icon>
        <% end %>
        <!-- bandage -->
        <%= f.radio_button :icon, "bandage" %>
        <%= f.label :icon, :value => "bandage" do%>
          <ion-icon name="bandage" class="transaction-img bandage" value="bandage"></ion-icon>
        <% end %>
      </div>
      </div>

       <div id="actions">
      <%= f.submit "Add Category", class: 'category-btnn'%>
    </div>
<% end %>

app/views/categories/index.html.erb
<section class='categories_controllers'>
  <div class="category-section">
     <h2 class="all-transaction">All Transactions</h2>

     <div class="container">
<% if @categories.length > 0 %>
      <ul class="category-lists-wrapper">
          <% @categories.each do |category| %>
           <%= link_to category_path(category.id), method: :get do %>
          <li class="category-li">
            <div class='desc'>
              <ion-icon name="<%= category.icon %>" class="list-image transaction-img <%= category.icon %>"></ion-icon>
              <span class="desc-text">
                <p><%= category.name %></p>
                <small><%= category.created_at.to_date.strftime("%d %b, %Y") %></small>
              </span>
            </div>
              <p class='strong'> $<%= category.businesses.sum(:amount) || '0.00'%>

              </p>
          </li>
          <% end %>
          <% end %>
      </ul>

     </div>
     

   <% else %>
          <p class="nil-category">No Category Added yet</p>
      <% end %>
  <div>
</div>

     <div class="add-category-wrapper">
        <div class="add-new-category">
          <%= button_to "Add new category", new_category_path, method: :get, class: 'category-btn' %>
        </div>
     </div>
</section>

app/views/categories/new.html.erb
 <nav class="navbar navbar-dark main-bg ">
  <div class="container">
 <%= link_to '←', categories_path(@category), class:'text-light text-decoration-none fs-2' %>
 <a class="navbar-brand" href="#">Categories</a>
 </div>
 </nav>
<div class = 'container py-4'>
  <h2 class = 'text-center'>ADD CATERGORY</h2>
  <div class = 'container w-70'>

    <%= render "form", category: @category %>


</div>
</div>
</div>

app/views/categories/show.html.erb
 <div class="container">
<section class="categories_controllers">
  <section class="category-section details ">
    <div class='payment'>
      <div class='desci'>
        <ion-icon id="list-img" name="<%= @category.icon %>"  class="transaction-img <%= @category.icon %>"></ion-icon>
        <span>
          <h3><%= @category.name %></h3>
        </span>
      </div>
      <p>TOTAL EXPENSES: <span class="all">$<%= @category.businesses.sum(:amount) || '0.00' %></span> </p>
  
    </div>
      <% if @transactions.present?%>
        <div class="transaction-container">
    <% @transactions.each do |transaction| %>
    <div class='transaction'>
      <span>
        <h3><%= transaction.name %></h3>
        <small><%= transaction.created_at.to_date.strftime("%d %b, %Y") %></small>
      </span>
         <span>
        <h3>$<%= transaction.amount %></h3>
      </span>
      <span>
         <%= button_to "Remove", category_business_path(@category,transaction), method: :delete, class: 'btn btn-danger' %>
      </span>
    </div>

   <% end %>
    <%= button_to "Delete Category", category_path, method: :delete, class: 'delete-categories btn btn-danger' %>
    </div>
    <% else %>
    <p></p>
    <% end %>

  </section>
  <div class='category-footer'>
    <%= button_to "Add new transaction", new_category_business_path(@category), method: :get, class: 'category-btnn' %>
  </div>
</section>
 </div>
 

app/views/layouts/_messages.html.erb
  <div class="container">
  <div class="row opened">
  <div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
<div class='style-alert alert alert-<%="#{name}"%> alert-dismissible fade show' role="alert">
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)%>
 
</div>
  <% end %>
  </div>
  </div>
  </div>


  <script>
const notification = document.querySelector(".opened")
setTimeout(() => {
    notification.classList.add("closed")
}, 2000);
  </script>

app/views/layouts/_nav.html.erb
<% if current_user %>
<nav class="navbar navbar-expand-lg bg-darki">
  <div class="container-fluid">
    <div class="navbar-brand">
        <%= link_to "Back", categories_path, class: "back" %> 
    </div>
     <div class="logo">Piggy</div>
  
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
   
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
         <%= link_to "All categories", categories_path, class: "nav-item nav-link" %>
           <%= link_to "New category", new_category_path, class: "nav-item nav-link" %>

         <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "nav-logout nav-link" %>
          <li class="prof">
          <% if current_user.avatar.attached? %> 
          <%= image_tag current_user.avatar, class: "nav-link avatar"%>
           <% else %>
            <%= image_tag "avatar.png", class: "avatar" %>
           <% end %>
           <%= link_to current_user.name, categories_path, class: "nav-item nav-link" %>
          
        </li>
      </ul>
    </div>
  </div>
</nav>
<% else %>
<nav class="navbar navbar-expand-lg bg-darki">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <%= image_tag "no-profile.jpg", class: "avatar"%>
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown"
      aria-expanded="false"
      aria-label="Toggle
                            navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
            <li><a class="nav-link" href="/users/sign_in">Login </a></li>
            <li><a class="nav-link" href="/users/sign_up">sign up</a></li>
         
        </li>
      </ul>
    </div>
  </div>
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  </head>

  <body>
    <%= render "layouts/nav" %>
       <%= render "layouts/messages" %>
    <%= yield %>

      <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
  </body>
</html>

app/views/welcome/index.html.erb
<div>
    <div class="ontop">
<div class=" jumbotron" data-aos="zoom-in"   data-aos-duration="3000">
    <div>    <h1 class="alpha">Piggy</h1>
   <p class="logo-text">start piggy. start saving :)</p>
</div>
<small class="smalll">Create an account?</small>
<%= link_to "Sign up now", "users/sign_up", class: "btn btn-success btn-lg btnn" %>

<small class="smalll">Already have an account?</small>
<%= link_to "Login", "users/sign_in", class: "btn btn-success btn-lg b" %>
</div>
</div>
</div>
 
<script>
    AOS.init()
</script>